#!/bin/zsh

. ~/.zsh/vars

alias mv='mv -v'
alias cp='cp -v'
alias rm='rm -iv'
#rebuild video indexes
alias mplayer='mplayer -idx'
alias ll='ls -ahl | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'

# Colorized files
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias myippub='echo $(curl -s http://ipwhats.appspot.com)'
## Si ne fonctionne plus : wget -q0 - http://cfaj.freeshell.org/ipaddr.cgi

alias pingg='ping -c 3 www.google.fr'
alias psaux='ps aux'


### adapt with install script
##alias 'pactest=~/Script/pactest'
##alias 'pacedit=vim ~/Scripts/pactest.py'
##alias 'sublime=/opt/sublime-text/sublime_text'
###
alias mount='mount | column -t'
alias du='cdu -idh'
alias free='freec -m'
alias disk_analyz='ncdu'



## Other stuffs
#alias rdesktopad='nohup rdesktop 10.5.1.205 -u administrateur -p olfeoolfeo -g 1820x980 &'
#alias rdesktopad2k8='nohup rdesktop 10.5.2.42 -u administrateur -p olfeoolfeo -g 1820x980 &'
#alias rdesktopseven='nohup rdesktop 10.5.2.44 -u administrateur -p olfeoolfeo -g 1820x980 &'